import type { AppState } from "../types/mail";
import { DEFAULT_MODE, getSavedMailbox } from "./constants";

export function createInitialState(): AppState {
  const mailbox = getSavedMailbox();
  return {
    runtime: { connected: false, mode: "connecting" },
    view: "start",
    mailbox,
    strategyMode: DEFAULT_MODE,
    loading: true,
    cards: [],
    actionCount: 0,
    scanState: null,
    history: [],
    scanStatus: "",
    scanError: "",
    isScanning: false,
    isCustomScanning: false,
    scanStepIndex: 0,
    scanStage: "",
    scanProgress: {},
    customPlans: [],
    customScanInput: "",
    customRunResult: null,
    customRunProgress: null,
    customTraceOpen: false,
    sourcesOpen: false,
    historyOpen: false,
    originalOpen: false,
    scanPlanOpen: false,
    scanPlan: null,
    selectedCard: null,
    selectedCardDetail: null,
    threadSummaryById: {},
    draftById: {},
    revisionById: {},
    replyModeById: {},
    threadContextExpanded: {},
    expandedDetails: {},
    snoozeMenuCardId: "",
    statusByCardId: {},
    lowerPriorityOpen: false,
    minimized: false,
    resultFilter: "all",
    llmProvider: "anna-llm",
    storageProvider: "local",
    generatingDraft: false,
    draftDots: "",
    summarizingThread: false,
    cleanupReadState: {},
    markingReadIds: {},
    gmailAuthStatus: { checked: false, authorized: true },
    askItemActions: {},
    askEditDraft: {},
    askHistory: [],
    askHistoryExpanded: {},
  };
}
