import type { AppState } from "../types/mail";
import { DEFAULT_MODE, getSavedMailbox } from "./constants";

export function createInitialState(): AppState {
  const mailbox = getSavedMailbox();
  return {
    runtime: { connected: false, mode: "connecting" },
    view: "start",
    mailbox,
    mailboxes: [],
    selectedMailboxes: mailbox ? [mailbox] : [],
    briefMailboxFilter: mailbox ? [mailbox] : [],
    allCards: [],
    strategyMode: DEFAULT_MODE,
    loading: true,
    cards: [],
    actionCount: 0,
    scanState: null,
    history: [],
    scanStatus: "",
    scanError: "",
    pendingAction: "",
    isScanning: false,
    restoredCardIds: new Set<string>(),
    isCustomScanning: false,
    scanStepIndex: 0,
    scanStage: "",
    scanProgress: {},
    customPlans: [],
    customScanInput: "",
    customRunResult: null,
    customRunProgress: null,
    customTraceOpen: false,
    sourcesOpen: false,
    historyOpen: false,
    memoryOpen: false,
    originalOpen: false,
    scanPlanOpen: false,
    contactMemories: [],
    selectedMemory: null,
    selectedMemoryKey: "",
    memoryLoading: false,
    memoryError: "",
    scanPlan: null,
    configMailbox: "",
    selectedCard: null,
    lastOpenedCardKey: "",
    selectedCardDetail: null,
    threadSummaryById: {},
    draftById: {},
    revisionById: {},
    replyModeById: {},
    threadContextExpanded: {},
    expandedDetails: {},
    snoozeMenuCardId: "",
    snoozeReasonsKey: "",
    expandAllConfigs: false,
    statusByCardId: {},
    lowerPriorityOpen: false,
    minimized: false,
    resultFilter: "all",
    llmProvider: "anna-llm",
    llmStatus: { status: "unknown", checked: false },
    storageProvider: "local",
    generatingDraft: false,
    gapAnswersByCard: {} as Record<string, Record<string, string>>,
    askGapAnswers: {} as Record<string, Record<string, string>>,
    askDraftsByKey: {} as Record<string, string>,
    draftDots: "",
    summarizingThread: false,
    cleanupReadState: {},
    cleanupBundle: null,
    markingReadIds: {},
    attachmentDownloads: {},
    gmailAuthStatus: { checked: false, authorized: true },
    gmailErrorPopup: null,
    askItemActions: {},
    askEditDraft: {},
    askHistory: [],
    askHistoryExpanded: {},
  };
}
